version: '3.8'

services:

  taxi-server:
    container_name: taxi-server
    build:
      context: ./server
    depends_on:
      - taxi-redis
      - taxi-database
    volumes:
      - ./server:/usr/src/app
    environment:
      - PGDATABASE=taxi
      - PGUSER=taxi
      - PGPASSWORD=taxi
      - PGHOST=taxi-database
      - REDIS_URL=redis://taxi-redis:6379/0
    ports:
      - 8003:8000
    command: python manage.py runserver 0.0.0.0:8000

  taxi-redis:
    container_name: taxi-redis
    image: redis:7-alpine
    expose:
      - 6379

  taxi-database:
    container_name: taxi-database
    image: postgres:15-alpine
    volumes:
      - taxi-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
    expose:
      - 5432

  taxi-client:
    container_name: taxi-client
    build:
      context: ./client
    depends_on:
      - taxi-server
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8003
      - REACT_APP_GOOGLE_MAPS_KEY=AIzaSyBHhkhvXIC16d-Jc5_P_IEswTP7wU_nPeY
    ports:
      - 3001:3000
    stdin_open: true
    command: yarn start

volumes:
  taxi-database:
